#!/bin/bash

GVMI_VERSION=1.2
GVMI_BUILD=1.2.5

ARG1=$1
ARG2=$2

if [[ $EUID -ne 0 ]]; then
    echo "GVMI requires root privileges"
    exit 1
fi

if [ "$ARG1" == "install" ] && [ "$ARG2" == "gvm11" ]; then
    source /etc/os-release
    if [ "$ID" == "debian" ] && [ "$VERSION_ID" == "10" ]; then
        source include/install/gvm11/debian10_install.sh
    else
        echo -e "\n OS NOT SUPPORTED\n"
    fi

elif [ "$ARG1" == "uninstall" ] && [ "$ARG2" == "gvm11" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""

elif [ "$ARG1" == "update" ] && [ "$ARG2" == "gvm11" ]; then
    source include/update/gvm11/debian10_update.sh

################## BEGIN - INSTALL CLIENT ##################
#elif [ "$ARG1" == "install" ] && [ "$ARG2" == "client" ]; then
#    cp ./gvmi /bin/gvmi
#	chown root:root /bin/gvmi
#	chmod 770 /bin/gvmi
#
#    echo ""
#    echo "GVMI CLIENT - INSTALLED"
#    echo ""
################## END - INSTALL CLIENT ##################


################## BEGIN - UNINSTALL CLIENT ##################
#elif [ "$ARG1" == "uninstall" ] && [ "$ARG2" == "client" ]; then
#    rm /bin/gvmi
#
#    echo ""
#    echo "GVMI CLIENT - UNINSTALLED"
#    echo ""
################## END - UNINSTALL CLIENT ##################


#elif [ "$ARG1" == "update" ] && [ "$ARG2" == "client" ]; then
#    echo ""
#    echo " Function not yet implemented"
#    echo ""

elif [ "$ARG1" == "start" ] && [ "$ARG2" == "gvm11" ]; then
    source include/start_stop/gvm11/debian10_start.sh

elif [ "$ARG1" == "stop" ] && [ "$ARG2" == "gvm11" ]; then
    source include/start_stop/gvm11/debian10_stop.sh



###################### BEGIN - HELP ##################
    elif [ "$ARG1" == "help" ] || [ "$ARG1" == "-h" ] || \
         [ "$ARG1" == "--help" ] || [ "$ARG1" == "-help" ] || \
         [ "$ARG1" == "--h" ] || [ "$ARG1" == "h" ]; then

        echo -e "\n GVMI - Version: $GVMI_VERSION   Build: $GVMI_BUILD\n"
        echo -e " Greenbone Vulnerability Management Installer\n\n"

        echo -e " commands:\n"
        echo "  install gvm11        GVM 11 installation"
        #echo "  install client       gvmi client installation"
        #echo "  uninstall client     uninstall gvmi client"
        echo "  version              provide gvmi version"
        echo "  help                 provide gvmi help"
        echo -e "\n"
####################### END - HELP ##################


################## BEGIN - VERSION ##################
elif [ "$ARG1" == "version" ] || [ "$ARG1" == "-v" ] || \
     [ "$ARG1" == "--version" ] || [ "$ARG1" == "-version" ] || \
     [ "$ARG1" == "--v" ] || [ "$ARG1" == "v" ]; then

    echo -e "\n GVMI - Version: $GVMI_VERSION   Build: $GVMI_BUILD\n"
    echo -e " Greenbone Vulnerability Management Installer\n"
################## END - VERSION ##################


else
    echo ""

fi
