#!/bin/bash

GVMI_VERSION=1.0
GVMI_BUILD=1.0.13

ARG1=$1
ARG2=$2

if [[ $EUID -ne 0 ]]; then
    echo "GVMI requires root privileges"
    exit 1
fi

if [ "$ARG1" == "install" ] && [ "$ARG2" == "gvm11" ]; then
    source /etc/os-release
    if [ "$ID" == "debian" ] && [ "$VERSION_ID" == "10" ]; then
        source include/install/gvm11/debian10_install.sh
    else
        echo -e "\n OS NOT SUPPORTED\n"
    fi

elif [ "$ARG1" == "uninstall" ] && [ "$ARG2" == "gvm11" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""

elif [ "$ARG1" == "update" ] && [ "$ARG2" == "gvm11" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""

elif [ "$ARG1" == "install" ] && [ "$ARG2" == "client" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""

elif [ "$ARG1" == "uninstall" ] && [ "$ARG2" == "client" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""

elif [ "$ARG1" == "update" ] && [ "$ARG2" == "client" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""

elif [ "$ARG1" == "start" ] && [ "$ARG2" == "gvm11" ]; then
    source include/start_stop/gvm11/debian10_start.sh

elif [ "$ARG1" == "stop" ] && [ "$ARG2" == "gvm11" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""

elif [ "$ARG1" == "help" ] && [ "$ARG2" == "" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""

elif [ "$ARG1" == "version" ] && [ "$ARG2" == "" ]; then
    echo ""
    echo " Function not yet implemented"
    echo ""

else
    echo ""

fi
